name: Collect Daily

on:
  schedule:
    - cron: '0 0 * * *' # Run at 12am every day
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - run: npm ci

    - run: node scripts/collect-daily.js

    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        BRANCH_NAME: 'main'