name: Collect

on: [push, pull_request]

jobs:
  collect:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Uses Node.js 18
      uses: actions/setup-node@v1
      with:
        node-version: 18

    - run: npm install

    - run: node scripts/collect.js

    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}